name: flame_fast_touch
description: Flame plugin to fix the problem of slow processing of touch events.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

# Add regular dependencies here.
dependencies:
  flame: ^1.9.1
  flutter:
    sdk: flutter
  # path: ^1.8.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
